apiVersion: v1
kind: Service
metadata:
  name: {{ include "issue-router.fullname" . }}-web-service
  labels:
    {{- include "issue-router.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "issue-router.selectorLabels" . | nindent 4 }}
