replicaCount: 1

image:
  repository: "renciorg/cam-kp-api"
  tag: "0.1.2-trapi-1.2"
  pullPolicy: Always


nameOverride: ""
fullnameOverride: ""


service:
  type: NodePort
  port: 8080

service:
  type: ClusterIP
  port: 8080
  resources:
    requests:
      memory: 20Gi
      cpu: 1
    limits:
      memory: 24Gi
      cpu: 3



ingress:
  host: ""
  class: ""
  timeout: 7200 # 1hr
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "250m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      keepalive_timeout 86400;
    nginx.ingress.kubernetes.io/connection-proxy-header: keep-alive
    nginx.ingress.kubernetes.io/send-timeout: "86400"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-keepalive-timeout: "86400