replicaCount: 1

image:
  repository: "renciorg/cam-kp-api"
  tag: "0.3-trapi-1.3"
  pullPolicy: Always


nameOverride: ""
fullnameOverride: ""

ingress:
  host: ""
  class: ""
  pathType: ImplementationSpecific
  timeout: 7200 # 1hr
  tls:
    enabled: true # We need a default to deploy this to RENCI
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "250m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      keepalive_timeout 86400;
    nginx.ingress.kubernetes.io/connection-proxy-header: keep-alive
    nginx.ingress.kubernetes.io/send-timeout: "86400"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-keepalive-timeout: "86400"
