{{- if semverCompare "<1.23-0" .Capabilities.KubeVersion.GitVersion  -}}
{{- if .Values.web.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: "{{- include "node-normalization-webserver.fullname" . }}-root-hpa"
  labels:
    app.kubernetes.io/component: replica
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{- include "node-normalization-webserver.fullname" . }}-root-server"
  minReplicas: {{ .Values.web.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.web.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.web.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.web.autoscaling.targetCPU }}
    {{- end }}
    {{- if .Values.web.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.web.autoscaling.targetMemory }}
    {{- end }}
{{- end }}

{{ else }}
{{- if .Values.web.autoscaling.enabled }}

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{- include "node-normalization-webserver.fullname" . }}-root-hpa"
  labels:
    app.kubernetes.io/component: replica
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{- include "node-normalization-webserver.fullname" . }}-root-server"
  minReplicas: {{ .Values.web.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.web.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.web.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.web.autoscaling.targetCPU }}
    {{- end }}
    {{- if .Values.web.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.web.autoscaling.targetMemory }}
    {{- end }}
{{- end }}
{{ end }}