# Default values for icees-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: renci/icees-api-server
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.5.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podSecurityContext: {}
  # fsGroup: 2000

service:
  type: ClusterIP
  port: 8080
  resources:
    requests:
      cpu: "2"
      memory: 16Gi
    limits:
      memory: "20Gi"
      cpu: "4"

redis:
  storage:
    size: 10Gi 

secrets:
  ICEES_HOST: db
  ICEES_DBUSER: icees_dbuser
  ICEES_DBPASS: icees_dbpass
  POSTGRES_PASSWORD: icees_postgres_password
  ICEES_DATABASE: icees_database

custom_envs:
  INSTANCE_NAME: pcd-dev
  ICEES_API_LOG_PATH: /iceesdata/pcd/logs
  OPENAPI_TITLE: ICEES PCD Instance API - development
  DB_PATH: /iceesdata/pcd/sqlite/example.db
  CONFIG_PATH: /iceesdata/pcd/config
  ICEES_API_INSTANCE_NAME: trapi-v1.2-pcd-dev
  ICEES_INFORES_CURIE: infores:icees-pcd
  OPENAPI_SERVER_MATURITY: development

ingress:
  host: icees-pcd-dev.apps.renci.org
  class: ""
  pathType: Prefix
