dataUrl: https://stars.renci.org/var/plater/bl-3.2.1/GtoPdb_Automat/e7d6b71aa6130b22/graph_e7d6b71aa6130b22.db.dump
metadataUrl: https://stars.renci.org/var/plater/bl-3.2.1/GtoPdb_Automat/e7d6b71aa6130b22/GtoPdb_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-3.2.1/GtoPdb_Automat/e7d6b71aa6130b22/meta_kg.json
testingDataUrl: https://stars.renci.org/var/plater/bl-3.2.1/GtoPdb_Automat/e7d6b71aa6130b22/sri_testing_data.json