dataUrl: https://stars.renci.org/var/plater/bl-3.0/GWASCatalog_Automat/bf55137c716a5613/graph_bf55137c716a5613.db.dump
metadataUrl: https://stars.renci.org/var/plater/bl-3.0/GWASCatalog_Automat/bf55137c716a5613/GWASCatalog_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-3.0/GWASCatalog_Automat/bf55137c716a5613/meta_kg.json
testingDataUrl: https://stars.renci.org/var/plater/bl-3.0/GWASCatalog_Automat/bf55137c716a5613/sri_testing_data.json