apiVersion: v1
kind: Service
metadata:
  name: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}-redis       
  labels:
    app.kubernetes.io/name: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}-redis
    app.kubernetes.io/instance: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}-redis
    server-type: redis
    trapi: "1.2"      
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}-redis
    app.kubernetes.io/instance: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}-redis
    server-type: redis
    trapi: "1.2"      
  type: {{ .Values.service.type }}

