dataUrl: https://stars.renci.org/var/plater/bl-3.2.1/IntAct_Automat/47923e95174e4f29/graph_47923e95174e4f29.db.dump
metadataUrl: https://stars.renci.org/var/plater/bl-3.2.1/IntAct_Automat/47923e95174e4f29/IntAct_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-3.2.1/IntAct_Automat/47923e95174e4f29/meta_kg.json
testingDataUrl: https://stars.renci.org/var/plater/bl-3.2.1/IntAct_Automat/47923e95174e4f29/sri_testing_data.json