dataUrl: https://stars.renci.org/var/plater/bl-2.1/merged_with_onto/VP-Uniref-2.1.1-09202021.dump
metadataUrl: https://stars.renci.org/var/plater/bl-2.1/viral-proteome/09202021/viral-proteome.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-2.1/viral-proteome/09202021/meta_kg.json
testingDataUrl: https://stars.renci.org/var/plater/bl-2.1/viral-proteome/09202021/sri_testing_data.json