# Default values for name-lookup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



webServer:
  replicaCount: 1
  service:
    port: 2433
    type: ClusterIP
  # container port
  port: 2433
  image:
    repository: ghcr.io/translatorsri/nameresolution
    tag: v1.3.3

dataUrl: "https://stars.renci.org/var/babel_outputs/2023jul13/solr/snapshot.backup.tar.gz"
forceRun: false

busybox:
  image:
    repository: busybox
    tag: "1.35"

# busybox:
#   image:
#     repository: busybox
#     tag: latest

solr:
  service:
    port: 8983
    type: ClusterIP
  # container port
  port: 8983
  heap_mem: "-Xms58G -Xmx58G"
  image:
    repository: solr
    tag: 9.1
  resources:
    requests:
      memory: "64Gi"
    limits:
      memory: "64Gi"
  # As of Babel 2023may18, we need 128G to store the
  # backup + uncompressed backup + Solr database
  # So 500Gi should be enough for the time being.
  storage: 500Gi

  initresources:
    requests:
      memory: 32Gi
      cpu: 1000m
    limits:
      memory: 64Gi
      cpu: 1000m

nameOverride: ""
fullnameOverride: ""

ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  pathType: "ImplementationSpecific"
  host:
  class:

blocklist:
  # The URL from where to download the blocklist. This should be a simple text file, where each line contains a CURIE.
  url: https://raw.githubusercontent.com/NCATSTranslator/Blocklists/main/blocklist.yaml
  # If a GitHub Personal Access Token is necessary to download the above file, it should be stored in a Kubernetes
  # secret as the value of a key named `github_personal_access_token`. To create this in Kubernetes, run:
  #   kubectl -n $NAMESPACE create secret generic ncats-translator-blocklist-secret --from-literal=github_personal_access_token=github_pat_...
  github_personal_access_token_secret: ncats-translator-blocklist-secret

x_trapi:
  maturity:
    value: "maturity"
  location:
    value: "location"
