# Default values for api-watchdog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: Always

app:
  updateCronInterval: "0 */24 * * *"

env:
  MAILGUN_API_URL: "msg email url"
  MAILGUN_API_TOKEN: "the key"
  MAILGUN_FROM: "from"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi
