apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aragorn-ranker.fullname" . }}
  labels:
    app: {{ include "aragorn-ranker.name" . }}
    trapi: "1.3"
spec:
  selector:
    matchLabels:
      app: {{ include "aragorn-ranker.name" . }}
      trapi: "1.3"
  template:
    metadata:
      labels:
        app: {{ include "aragorn-ranker.name" . }}
        trapi: "1.3"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/env-config-map.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-web-container
          command:
            - 'uvicorn'
          args:
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "{{ .Values.app.port}}"
            - '--workers'
            - '4'
            - '--root-path'
            - '{{.Values.ingress.path}}'
            - 'ranker.server:APP'
          envFrom:
            - configMapRef:
                name: {{ include "aragorn-ranker.fullname" . }}-configmap
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
          - containerPort: {{ .Values.app.port }}
            name: http
            protocol: TCP
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      restartPolicy: Always
