apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "strider.fullname" . }}-configmap
data:
  OPENAPI_SERVER_URL: https://{{ .Values.ingress.strider.host }}
  OPENAPI_SERVER_MATURITY: {{ .Values.x_trapi.maturity.value }}
  OPENAPI_SERVER_LOCATION: {{ .Values.x_trapi.location.value }}
  ROOT_PATH: {{ .Values.ingress.path }}
  OMNICORP_URL: {{ .Values.env.omnicorp }}
  NORMALIZER_URL: {{ .Values.env.nodenorm }}
  BIOLINK_URL: {{ .Values.env.biolink }}
  MAX_PROCESS_TIME: "{{ .Values.env.max_process_time }}"
  REDIS_EXPIRATION: "{{ .Values.env.redis_expiration }}"
  REDIS_PASSWORD: {{ .Values.env.redis_password }}
  REDIS_HOST: {{ .Values.env.redis_host }}
  REDIS_PORT: "{{ .Values.redis.service.port }}"
