apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "strider.fullname" . }}-gunicorn-conf
data:
  uvicorn_custom.py: |-
    from uvicorn.workers import UvicornWorker
    class SubPathWorker(UvicornWorker):
       CONFIG_KWARGS = {"root_path": "{{ .Values.ingress.path }}" }