apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "strider.fullname" . }}-logs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.strider.logsPVCSize }}