apiVersion: v1
kind: Service
metadata:
  name: {{ include "strider.fullname" . }}-redis-service
  labels:
    {{- include "strider.labels" . | nindent 4 }}
    service-type: redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379
      protocol: TCP
      name: redis-port
  selector:
    {{- include "strider.selectorLabels" . | nindent 4 }}
    service-type: redis
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "strider.fullname" . }}-redis-insights-service
  labels:
    {{- include "strider.labels" . | nindent 4 }}
    service-type: redis-insights
spec:
  type: {{ .Values.redisInsights.service.type }}
  ports:
    - port: {{ .Values.redisInsights.service.port }}
      targetPort: 8001
      protocol: TCP
      name: redis-insights-port
  selector:
    {{- include "strider.selectorLabels" . | nindent 4 }}
    service-type: redis-insights
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "strider.fullname" . }}-web-service
  labels:
    {{- include "strider.labels" . | nindent 4 }}
    service-type: webserver
spec:
  type: {{ .Values.strider.service.type }}
  ports:
    - port: {{ .Values.strider.service.port }}
      targetPort: {{ .Values.strider.container.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "strider.selectorLabels" . | nindent 4 }}
    service-type: webserver
