{{- if .Values.kpRegistry.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "strider.fullname" . }}-kp-service
  labels:
    {{- include "strider.labels" . | nindent 4 }}
    service-type: database
spec:
  type: {{ .Values.kpRegistry.service.type }}
  ports:
    - port: {{ .Values.kpRegistry.service.port }}
      targetPort: 4983
      protocol: TCP
      name: http
  selector:
    {{- include "strider.selectorLabels" . | nindent 4 }}
    service-type: database
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "strider.fullname" . }}-web-service
  labels:
    {{- include "strider.labels" . | nindent 4 }}
    service-type: webserver
spec:
  type: {{ .Values.strider.service.type }}
  ports:
    - port: {{ .Values.strider.service.port }}
      targetPort: {{ .Values.strider.container.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "strider.selectorLabels" . | nindent 4 }}
    service-type: webserver
