apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "strider.fullname" . }}
  labels:
    {{- include "strider.labels" . | nindent 4 }}
    service-type: webserver
spec:
  replicas: {{ .Values.strider.replicaCount }}
  {{ if .Values.strider.strategy }}
  strategy:
    type: {{ .Values.strider.strategy }}
  {{ end }}
  selector:
    matchLabels:
      {{- include "strider.selectorLabels" . | nindent 6 }}
      service-type: webserver
  template:
    metadata:
      labels:
        {{- include "strider.selectorLabels" . | nindent 8 }}
        service-type: webserver
    spec:
      {{- with .Values.strider.securityContext }}
      securityContext:
        {{ . | toYaml | nindent 8 }}
      {{- end }}
      containers:

        - name: {{ .Chart.Name }}-webserver
          image: "{{ .Values.strider.image.repository }}:{{ .Values.strider.image.tag }}"
          imagePullPolicy: "{{ .Values.strider.image.imagePullPolicy }}"
          env:
            {{ if .Values.HTTPS_PROXY }}
            - name: "HTTPS_PROXY"
              value: "{{ .Values.HTTPS_PROXY }}"
            {{ end }}
            {{ if .Values.NO_PROXY }}
            - name: "NO_PROXY"
              value: "{{ .Values.NO_PROXY}}"
            {{ end }}
            - name: REDIS_HOST
              value: "{{ include "strider.fullname" . }}-redis-service"
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: KPREGISTRY_URL
              {{- if .Values.kpRegistry.enabled }}
              value: "http://{{ include "strider.fullname" . }}-kp-service:{{ .Values.kpRegistry.service.port }}"
              {{- else }}
              value: "https://kp-registry.renci.org"
              {{- end }}
            - name: OMNICORP_URL
              value: {{ .Values.strider.env.OMNICORP_URL }}
            - name: REDIS_URL
              value: "redis://{{ include "strider.fullname" . }}-redis-service:{{ .Values.redis.service.port }}"
            - name: OPENAPI_SERVER_URL
              value: https://{{ .Values.ingress.strider.host }}
            - name: NORMALIZER_URL
              value: {{ .Values.strider.env.NORMALIZER_URL }}
            - name: "OPENAPI_SERVER_MATURITY"
              value: "{{ .Values.x_trapi.maturity.value }}"
            - name: "OPENAPI_SERVER_LOCATION"
              value: "{{ .Values.x_trapi.location.value }}"
            - name: "ROOT_PATH"
              value: "/1.3"
          command:
            - 'uvicorn'
          args:
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "{{ .Values.strider.container.port }}"
            - "--root-path"
            - "/1.3"
            - "--workers"
            - "{{ .Values.strider.uvicornWorkerCount }}"
            - "strider.server:APP"
          ports:
            - name: http
              containerPort: {{ .Values.strider.container.port }}
              protocol: TCP
          {{ if .Values.probes.strider.enabled }}
          livenessProbe:
            exec:
              command:
              - /strider_health.sh
              - "{{ .Values.probes.strider.timeoutSeconds }}"
            failureThreshold: {{ .Values.probes.strider.failureThreshold }}
            periodSeconds: {{ .Values.probes.strider.period }}
            successThreshold: {{ .Values.probes.strider.successThreshold }}
            timeoutSeconds: {{ .Values.probes.strider.timeoutSeconds }}
          {{ end }}
          {{ if .Values.strider.resources }}
          resources: {{ toYaml .Values.strider.resources | nindent 12 }}
          {{ end }}
          volumeMounts:
          - name: {{ include "strider.fullname" . }}-health-scripts
            mountPath: /strider_health.sh
            subPath: strider_health.sh
          - name: {{ include "strider.fullname" . }}-logs-pvc
            mountPath: /app/logs/
      volumes:
      - name: {{ include "strider.fullname" . }}-health-scripts
        configMap:
          name: {{ include "strider.fullname" . }}-heath-configmap
          defaultMode: 0777
      - name: {{ include "strider.fullname" . }}-logs-pvc
        persistentVolumeClaim:
          claimName: {{ include "strider.fullname" . }}-logs-pvc