apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "strider.fullname" . }}-update-kp-registry
spec:
  schedule: "{{ .Values.strider.updateCronInterval }}"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job-container
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - wget
            - "http://{{ include "strider.fullname" . }}-web-service:{{ .Values.strider.service.port }}/refresh"
            - --post-data
            - ""
          restartPolicy: OnFailure
