apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{  include "benchmark.fullname" . }}-config-map
  name: {{  include "benchmark.fullname" . }}-config-map
data:
  custom.conf: |-
    location / {
        autoindex on;
    }