apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cam-kp-api.fullname" . }}-trapi-1-2-deployment
  labels:
    app.kubernetes.io/name: {{ include "cam-kp-api.fullname" . }}-trapi-1-2-deployment
    app.kubernetes.io/instance: {{ include "cam-kp-api.fullname" . }}-trapi-1-2-deployment
    service-type: webserver
    trapi: "1.2"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cam-kp-api.fullname" . }}-trapi-1-2-deployment
      app.kubernetes.io/instance: {{ include "cam-kp-api.fullname" . }}-trapi-1-2-deployment
      service-type: webserver
      trapi: "1.2"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cam-kp-api.fullname" . }}-trapi-1-2-deployment
        app.kubernetes.io/instance: {{ include "cam-kp-api.fullname" . }}-trapi-1-2-deployment
        service-type: webserver
        trapi: "1.2"
    spec:
      containers:
        - name: {{ include "cam-kp-api.fullname" . }}-trapi-1-2-server
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}-trapi-1.2
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
          - name: SPARQL_ENDPOINT
            value: {{ .Values.app.sparql_endpoint }}
          - name: CAM_KP_LOG_LEVEL
            value: {{ .Values.app.log_level }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          resources: {{ toYaml .Values.service.resources | nindent 12 }}
