apiVersion: v1
kind: Service
metadata:
  name: {{ include "cam-kp-api.fullname" . }}-trapi-1-3-service
  labels:
    app.kubernetes.io/name: {{ include "cam-kp-api.fullname" . }}-trapi-1-3-service
    app.kubernetes.io/instance: {{ include "cam-kp-api.fullname" . }}-trapi-1-3-service
    service-type: webserver
    trapi: "1.3"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "cam-kp-api.fullname" . }}-trapi-1-3-deployment
    app.kubernetes.io/instance: {{ include "cam-kp-api.fullname" . }}-trapi-1-3-deployment
    service-type: webserver
    trapi: "1.3"
