apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aragorn.fullname" . }}-gunicorn-conf
data:
  uvicorn_custom_aragorn.py: |-
    from uvicorn.workers import UvicornWorker
    class SubPathWorker(UvicornWorker):
       CONFIG_KWARGS = {"root_path": "/aragorn" }
  uvicorn_custom_robokop.py: |-
    from uvicorn.workers import UvicornWorker
    class SubPathWorker(UvicornWorker):
       CONFIG_KWARGS = {"root_path": "/robokop" }